/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Arbol;
import EDD.Lista;
import Funciones.MostrarArbol;
import Funciones.Validar;
import static Interfaces.Inicio.arbolGenealogico;
import javax.swing.JOptionPane;
import proyecto2edds.Persona;

/**
 *
 * @author Enrique León
 */
public class BuscarNombre extends javax.swing.JFrame {

    private Validar validar = new Validar();
    private String[] resultadoBusqueda;

    public BuscarNombre() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarNombre = new javax.swing.JButton();
        inputNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoStr = new javax.swing.JTextArea();
        volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputIndice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        verDatallePersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                formHierarchyChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarNombre.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        buscarNombre.setText("Buscar");
        buscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(buscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));
        jPanel1.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 300, -1));

        resultadoStr.setColumns(20);
        resultadoStr.setRows(5);
        jScrollPane1.setViewportView(resultadoStr);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 280, 120));

        volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Buscar por Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Resultados de la búsqueda:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));
        jPanel1.add(inputIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 280, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Ingrese el número asociado a la persona para acceder a su información:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        verDatallePersona.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        verDatallePersona.setText("Ver detalle");
        verDatallePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDatallePersonaActionPerformed(evt);
            }
        });
        jPanel1.add(verDatallePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formHierarchyChanged

    }//GEN-LAST:event_formHierarchyChanged

    private void buscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNombreActionPerformed
        if (!inputNombre.getText().isEmpty()) {
            String nombre = inputNombre.getText();
            Lista resultados = arbolGenealogico.getHashTable().buscarNombre(nombre);

            if (!resultados.isEmpty()) {
                String[] nombresResultados = new String[resultados.getSize()];

                for (int i = 0; i < resultados.getSize(); i++) {
                    Persona persona = (Persona) resultados.getValor(i);
                    if (persona.getMote() != null) {
                        nombresResultados[i] = persona.getMote();
                    } else {
                        nombresResultados[i] = persona.getNombre() + " " + persona.getNumeral();
                    }
                }

                resultadoBusqueda = nombresResultados;

                String resultado = "";

                for (int i = 0; i < nombresResultados.length; i++) {
                    int indice = i + 1;
                    resultado += indice + ": " + nombresResultados[i] + "\n";
                }

                resultadoStr.setText(resultado);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron coincidencia con el nombre buscado");
            }

            inputNombre.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "El input no puede estar vacio");
        }


    }//GEN-LAST:event_buscarNombreActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void verDatallePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDatallePersonaActionPerformed
       if (resultadoBusqueda == null || resultadoBusqueda[0] == null) {
            JOptionPane.showMessageDialog(null, "No hay resultados para ver detalles");
        } else {
            if (!inputIndice.getText().isEmpty() && !"".equals(inputIndice.getText())) {
                String indiceStr = inputIndice.getText();
                if (validar.ValidarNumeros(indiceStr) != -1) {
                    int indice = validar.ValidarNumeros(indiceStr) - 1;
                    if (validar.validarIndice(resultadoBusqueda.length - 1, 0, indice)) {
                        String clave = resultadoBusqueda[indice];

                        Arbol descendencia = new Arbol();

                        descendencia.setRoot(arbolGenealogico.getArbol().buscar(clave));
                        
                        System.setProperty("org.graphstream.ui", "swing");

                        MostrarArbol mostrar = new MostrarArbol(descendencia);
                        mostrar.setVisible(true);
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(null, "El numero esta fuera del indice");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debe ingresar un numero.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El input no puede estar vacio");
            }
        }
                
    }//GEN-LAST:event_verDatallePersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarNombre;
    private javax.swing.JTextField inputIndice;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultadoStr;
    private javax.swing.JButton verDatallePersona;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
