/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.MostrarArbol;
import static Interfaces.Inicio.arbolGenealogico;

/**
 *
 * @author eabdf
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.nombreLinajeMenu.setText(arbolGenealogico.getNombreLinaje());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarNombre = new javax.swing.JButton();
        buscarTitulo = new javax.swing.JButton();
        nombreLinajeMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listarGeneraciones = new javax.swing.JButton();
        cargarLinaje = new javax.swing.JButton();
        antepasados = new javax.swing.JButton();
        verRegistros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarNombre.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        buscarNombre.setText("Buscar por Nombre");
        buscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(buscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        buscarTitulo.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        buscarTitulo.setText("Buscar por Título");
        buscarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTituloActionPerformed(evt);
            }
        });
        jPanel1.add(buscarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        nombreLinajeMenu.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        nombreLinajeMenu.setText("Nombre del Linaje");
        jPanel1.add(nombreLinajeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 240, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("MENÚ PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 290, -1));

        listarGeneraciones.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        listarGeneraciones.setText("Generaciones");
        listarGeneraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarGeneracionesActionPerformed(evt);
            }
        });
        jPanel1.add(listarGeneraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        cargarLinaje.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        cargarLinaje.setText("Cargar Linaje");
        cargarLinaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarLinajeActionPerformed(evt);
            }
        });
        jPanel1.add(cargarLinaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        antepasados.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        antepasados.setText("Antepasados");
        antepasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antepasadosActionPerformed(evt);
            }
        });
        jPanel1.add(antepasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        verRegistros.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        verRegistros.setText("Ver Registros");
        verRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRegistrosActionPerformed(evt);
            }
        });
        jPanel1.add(verRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNombreActionPerformed
        BuscarNombre buscarPorNombre = new BuscarNombre();
        this.dispose();
    }//GEN-LAST:event_buscarNombreActionPerformed

    private void buscarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTituloActionPerformed
        BuscarTitulo buscarPorTitulo = new BuscarTitulo();
        this.dispose();
    }//GEN-LAST:event_buscarTituloActionPerformed

    private void listarGeneracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarGeneracionesActionPerformed
        ListarGeneraciones listaGeneracion = new ListarGeneraciones();
        this.dispose();
    }//GEN-LAST:event_listarGeneracionesActionPerformed

    private void cargarLinajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarLinajeActionPerformed
        arbolGenealogico.destruir();
        Inicio inicio = new Inicio();
        this.dispose();
    }//GEN-LAST:event_cargarLinajeActionPerformed

    private void antepasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antepasadosActionPerformed
        Antepasados antepasados = new Antepasados();
        this.dispose();
    }//GEN-LAST:event_antepasadosActionPerformed

    private void verRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRegistrosActionPerformed
        System.setProperty("org.graphstream.ui", "swing");

        MostrarArbol mostrar = new MostrarArbol(arbolGenealogico.getArbol());
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antepasados;
    private javax.swing.JButton buscarNombre;
    private javax.swing.JButton buscarTitulo;
    private javax.swing.JButton cargarLinaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listarGeneraciones;
    private javax.swing.JLabel nombreLinajeMenu;
    private javax.swing.JButton verRegistros;
    // End of variables declaration//GEN-END:variables
}
